"""Delete field login

Revision ID: 10938791b26f
Revises: 8f295ba0b355
Create Date: 2024-10-01 04:05:44.322350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10938791b26f'
down_revision: Union[str, None] = '8f295ba0b355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('login', mysql.VARCHAR(length=100), nullable=False)
    )
    # ### end Alembic commands ###
