"""Update table

Revision ID: 8f295ba0b355
Revises: 05ac4ca80f58
Create Date: 2024-10-01 03:21:22.966357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f295ba0b355'
down_revision: Union[str, None] = '05ac4ca80f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=320),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###
